object Modules {
    val navigation = ":navigation"
    val core = ":core"
    val app = ":app"
    val ui = ":ui"
    val extensions = ":extensions"
    val di = ":di"
    val splash = ":splash"
    val tilawat = ":tilawat"
    val recitation = ":recitation"
    val translations = ":translations"
    val home = ":home"
    val sidesheet = ":sidesheet"
    val translators = ":translators"
}