object BuildDependenciesVersions {

    const val gradle = "3.6.3"
    const val googleServices = "4.3.3"
    const val kotlin = "1.3.72"
    const val materialDesignNew = "1.2.0-alpha05"
    const val appcompat = "1.2.0-alpha03"
    const val coroutines = "1.3.5"
    const val recyclerview = "1.2.0-alpha01"
    const val navigation = "2.3.0-alpha04"
    const val lifeCycle = "2.2.0"
    const val coreKTX = "1.2.0"
    const val activityKTX = "1.1.0"
    const val fragmentKTX = "1.2.4"
    const val constraintLayout = "1.1.3"
    const val timber = "4.7.1"
    const val okhttp3 = "4.5.0"
    const val retrofit = "2.8.1"
    const val cardview = "1.0.0"
    const val swiperefreshlayout = "1.1.0-beta01"
    const val koin = "2.1.5"
    const val exoPlayer = "2.10.0"
    const val media = "1.1.0"

    const val jUnitTest = "4.12"
    const val mockk = "1.9.3"
    const val jUnitTestExt = "1.1.1"
    const val androidXTest = "1.2.0"
    const val androidXTestExpresso = "3.2.0"

}