object BuildModules {
    const val navigation = ":navigation"
    const val core = ":core"
    const val ui = ":ui"
    const val extensions = ":extensions"
    const val di = ":di"
    const val splash = ":splash"
    const val tilawat = ":tilawat"
    const val recitation = ":recitation"
    const val translations = ":translations"
    const val home = ":home"
    const val sidesheet = ":sidesheet"
    const val reciters = ":reciters"
    const val listpager = ":listpager"
    const val daos = ":daos"
    const val audioplayer = ":audioplayer"
    const val media = ":media"
    const val shared = ":shared"
    const val repository = ":repository"
    const val network = ":repository:network"
    const val storage = ":repository:storage"
    const val repositoryDaos = ":repository:daos"
}